import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFD54F',
    height: 90, // Tinaasan ang height para sa tamang vertical alignment ng title
    paddingTop: Platform.OS === 'ios' ? 40 : 0,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 20,
    // Sentrong alignment base sa taas ng header
    top: Platform.OS === 'ios' ? 55 : 45, 
    padding: 10,
    borderRadius: 12,
    zIndex: 20,
  },
  backIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  headerTitle: {
    fontSize: 24,
    color: '#2D1606',
    fontFamily: 'Poppins-Bold',
    fontWeight: '900',
    textAlign: 'center',
  },
  avatarSection: {
    alignItems: 'center',
    // Hinihila pabalik sa taas (negative) para sa overlap effect sa dilaw
    marginTop: 40, 
    marginBottom: 10,
    zIndex: 10,
  },
  avatarWrapper: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  avatarImg: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  editBadge: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: '#3E2723',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  editIcon: {
    width: 16,
    height: 16,
    tintColor: '#FFD54F',
  },
  changeText: {
    marginTop: 10,
    fontSize: 14,
    color: '#8D8D8D',
    fontFamily: 'Poppins-Medium',
  },
  settingsContainer: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 25,
    borderRadius: 35,
    paddingHorizontal: 20,
    paddingVertical: 30,
    marginTop: 10,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 15,
  },
  inputGroup: {
    marginBottom: 20,
  },
  fieldLabel: {
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
    color: '#BDBDBD',
    marginBottom: 8,
    marginLeft: 5,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  textInput: {
    backgroundColor: '#F0F2F5',
    borderRadius: 15,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#2D1606',
    fontFamily: 'Poppins-Medium',
    textAlign: 'left', // Siguradong pantay ang text sa kaliwa
  },
  saveBtn: {
    backgroundColor: '#FFD54F',
    borderRadius: 15,
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 10,
  },
  saveBtnText: {
    color: '#2D1606',
    fontSize: 18,
    fontFamily: 'Poppins-Bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    padding: 25,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
    color: '#2D1606',
    marginBottom: 20,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 15,
    marginBottom: 25,
  },
  avatarOption: {
    borderWidth: 3,
    borderColor: 'transparent',
    borderRadius: 45,
    padding: 2,
  },
  activeAvatarOption: {
    borderColor: '#FFD54F',
  },
  modalAvatarImg: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  closeBtn: {
    marginTop: 10,
  },
  closeBtnText: {
    color: '#FF5252',
    fontFamily: 'Poppins-Bold',
    fontSize: 16,
  },
});