import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFD54F', // Pinanatili ang yellow header base sa image_fc6bc3.png
    height: 80,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    padding: 8,
    borderRadius: 12,
  },
  backIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    tintColor: '#2D1606',
  },
  headerTitle: {
    fontSize: 24,
    color: '#2D1606',
    fontFamily: 'Poppins-Bold',
    fontWeight: '900',
  },
  scrollBody: {
    backgroundColor: '#FFFFFF',
  },
  contentWrapper: {
    paddingTop: 30,
    paddingBottom: 100,
  },
  whiteCardWrapper: {
    paddingHorizontal: 16,
  },
  whiteCard: {
    backgroundColor: '#FFFDF5',
    borderRadius: 32,
    padding: 22,
    marginBottom: 15,
    elevation: 7,
    shadowColor: '#8A6200',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: '#F4E7BF',
  },
  cardLabel: {
    fontSize: 13,
    fontFamily: 'Poppins-Bold',
    color: '#374151',
    marginBottom: 15,
    opacity: 0.8,
  },
  milestoneDesc: {
    fontSize: 14,
    color: '#6B7280',
    fontFamily: 'Poppins-Medium',
    marginBottom: 15,
  },
  progressBarBg: {
    height: 10,
    backgroundColor: '#F3E9D8',
    borderRadius: 5,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#FFD54F',
    borderRadius: 5,
  },
  
  // HOME CARD STYLES COPIED
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFDF5',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F4E7BF',
  },
  activeDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#D97706',
    marginRight: 6,
  },
  streakBadgeText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 9,
    color: '#8A6200',
    letterSpacing: 0.8,
  },
  progressTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 115,
  },
  streakSmallLabel: {
    fontFamily: 'Poppins-Bold',
    fontSize: 10,
    color: '#9CA3AF',
    letterSpacing: 1.3,
    marginBottom: 2,
  },
  streakNumberRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  streakNumberLarge: {
    fontFamily: 'Poppins-Bold',
    fontSize: 58,
    color: '#374151',
    lineHeight: 64,
    letterSpacing: -2,
  },
  streakDays: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: '#8A6200',
    marginLeft: 7,
    letterSpacing: 1,
  },
  superStreakBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#374151',
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 15,
    marginTop: 4,
  },
  superStreakText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 9,
    color: '#FFD54F',
    letterSpacing: 0.4,
  },
  tripleFlameWrapper: {
    width: 140, // Enlarge wrapper
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginRight: 5,
  },
  centerFlame: {
    width: 140, // Increased from 100 for bigger asset
    height: 140,
    zIndex: 2,
  },
  weeklyProgressContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 23,
    paddingHorizontal: 13,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: '#F3E9D8',
    marginTop: 10,
  },
  weeklyProgressTitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: 9,
    color: '#9CA3AF',
    letterSpacing: 1.2,
    marginBottom: 10,
    textAlign: 'center',
  },
  largeWeekRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginLeft: -4, // Shift slightly left as requested by user
  },
  largeDayBox: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayCircleLarge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  dayActive: {
    backgroundColor: '#FFD54F',
    borderWidth: 2,
    borderColor: '#D97706',
    elevation: 3,
    shadowColor: '#B45309',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  dayInactive: {
    backgroundColor: '#F5F1EA',
    borderWidth: 1,
    borderColor: '#E8DED0',
  },
  checkMarkLarge: {
    fontSize: 13,
    color: '#374151',
    fontFamily: 'Poppins-Bold',
  },
  lockIcon: {
    fontSize: 9,
    opacity: 0.35,
  },
  largeDayText: {
    fontSize: 8.5,
    fontFamily: 'Poppins-Bold',
    color: '#9CA3AF',
    letterSpacing: 0.2,
  },
});